// Generated by Xata Codegen 0.29.3. Please do not edit.
import { buildClient } from "@xata.io/client";
import type {
  BaseClientOptions,
  SchemaInference,
  XataRecord,
} from "@xata.io/client";

const tables = [
  {
    name: "PDFDcouments",
    columns: [
      { name: "file_name", type: "string" },
      {
        name: "file_content",
        type: "file",
        file: { defaultPublicAccess: true },
      },
    ],
  },
  {
    name: "PDFDocuments",
    columns: [
      { name: "file_name", type: "string" },
      {
        name: "file_content",
        type: "file",
        file: { defaultPublicAccess: true },
      },
    ],
  },
] as const;

export type SchemaTables = typeof tables;
export type InferredTypes = SchemaInference<SchemaTables>;

export type PDFDcouments = InferredTypes["PDFDcouments"];
export type PDFDcoumentsRecord = PDFDcouments & XataRecord;

export type PDFDocuments = InferredTypes["PDFDocuments"];
export type PDFDocumentsRecord = PDFDocuments & XataRecord;

export type DatabaseSchema = {
  PDFDcouments: PDFDcoumentsRecord;
  PDFDocuments: PDFDocumentsRecord;
};

const DatabaseClient = buildClient();

const defaultOptions = {
  databaseURL:
    "https://NandhniV25-s-workspace-396fgt.ap-southeast-2.xata.sh/db/pdf-summary-blob",
};

export class XataClient extends DatabaseClient<DatabaseSchema> {
  constructor(options?: BaseClientOptions) {
    super({ ...defaultOptions, ...options }, tables);
  }
}

let instance: XataClient | undefined = undefined;

export const getXataClient = () => {
  if (instance) return instance;

  instance = new XataClient();
  return instance;
};
